name: Build Chrome Extension

on:
  push:
    branches: [ "main" ]

jobs:
  build-crx:
    name: Build CRX file
    uses: cardinalby/.github/workflows/webext-buildtools-pack-extension-dir-action@v1
    with:
      extensionDir: 'chrome-extension'
      zipFilePath: 'chrome-extension/zip/let-me-multitask-bro.zip'
      crxFilePath: 'chrome-extension/crx/let-me-multitask-bro.crx'
      privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}
      # The following is optional if you need update.xml file
      updateXmlPath: 'crx/update.xml'
      updateXmlCodebaseUrl: 'https://raw.githubusercontent.com/rosettast0ned/let-me-multitask-bro/main/chrome-extension/crx/let-me-multitask-bro.crx'
